//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency_2nd_Semester_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int GenderID { get; set; }
        public int AgeGroupID { get; set; }
        public int TourID { get; set; }
        public int NumberOfParticipants { get; set; }
        public System.DateTime TourDate { get; set; }
        public int PaymentMethodID { get; set; }
        public string SpecialComments { get; set; }
        public bool TermsAccepted { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual AgeGroup AgeGroup { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
