//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency_2nd_Semester_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrazsToursTravelAgencyDBEntitiesConString : DbContext
    {
        public BrazsToursTravelAgencyDBEntitiesConString()
            : base("name=BrazsToursTravelAgencyDBEntitiesConString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeGroup> AgeGroups { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
    }
}
